name: java
on:
  push:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 13

      # Execute Gradle commands in GitHub Actions workflows
      # => https://github.com/marketplace/actions/gradle-command
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: runOnGitHub
          build-root-directory: Houseclub/
     #     dependencies-cache-enabled: true
     #     configuration-cache-enabled: true
